/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;


/**
 *
 * @author TheLoli
 */
public class cadastro extends javax.swing.JFrame {

    public cadastro() {
        initComponents();
        painel_mascara.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        sep_name = new javax.swing.JSeparator();
        lb_senha = new javax.swing.JLabel();
        sep_senha = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        bt_entrar = new javax.swing.JButton();
        lb_contarapida = new javax.swing.JLabel();
        lb_criarconta = new javax.swing.JLabel();
        painel_mascara = new javax.swing.JPanel();
        lb_contorno = new javax.swing.JLabel();
        lb_greenpeace = new javax.swing.JLabel();
        lb_futuro = new javax.swing.JLabel();
        lb_imgfloresta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 32, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_name.setForeground(new java.awt.Color(115, 200, 44));
        lb_name.setText("Nome");
        jPanel1.add(lb_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txt_name.setBackground(new java.awt.Color(51, 52, 54));
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setBorder(null);
        txt_name.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
        });
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 290, 30));
        jPanel1.add(sep_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 290, 20));

        lb_senha.setForeground(new java.awt.Color(51, 52, 54));
        lb_senha.setText("Senha");
        jPanel1.add(lb_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        jPanel1.add(sep_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 290, 20));

        jPasswordField1.setBackground(new java.awt.Color(51, 52, 54));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 290, 30));

        bt_entrar.setBackground(new java.awt.Color(115, 200, 44));
        bt_entrar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 290, 40));

        lb_contarapida.setForeground(new java.awt.Color(51, 52, 54));
        lb_contarapida.setText("Para um cadastro rápido favor selecione uma das opções abaixo:");
        jPanel1.add(lb_contarapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        lb_criarconta.setForeground(new java.awt.Color(51, 52, 54));
        lb_criarconta.setText("Se ainda não possui uma conta e desaja fazer um cadastro clique aqui.");
        lb_criarconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_criarcontaMouseClicked(evt);
            }
        });
        jPanel1.add(lb_criarconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 20));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 0, 450, 500);

        painel_mascara.setBackground(new java.awt.Color(0, 0, 0));
        painel_mascara.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_contorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/contornogreen.png"))); // NOI18N
        painel_mascara.add(lb_contorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lb_greenpeace.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        lb_greenpeace.setForeground(new java.awt.Color(115, 200, 44));
        lb_greenpeace.setText("Greenpeace");
        painel_mascara.add(lb_greenpeace, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        lb_futuro.setFont(new java.awt.Font("Harlow Solid Italic", 0, 14)); // NOI18N
        lb_futuro.setForeground(new java.awt.Color(255, 255, 255));
        lb_futuro.setText("Por um futuro menos poluído.");
        painel_mascara.add(lb_futuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        getContentPane().add(painel_mascara);
        painel_mascara.setBounds(0, 0, 380, 500);

        lb_imgfloresta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/floresta-amazonica-343759751.jpg"))); // NOI18N
        getContentPane().add(lb_imgfloresta);
        lb_imgfloresta.setBounds(0, 0, 830, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained

        sep_senha.setBackground(new Color(115,200,44));
        lb_senha.setForeground(new Color(115,200,44));
        lb_name.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusGained

        sep_senha.setBackground(new Color(115,200,44));
        lb_name.setForeground(new Color(115,200,44));
        lb_senha.setForeground(new Color(51,52,54));
    }//GEN-LAST:event_txt_nameFocusGained

    private void lb_criarcontaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_criarcontaMouseClicked
        new login().setVisible(true);
    }//GEN-LAST:event_lb_criarcontaMouseClicked

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed

    }//GEN-LAST:event_bt_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lb_contarapida;
    private javax.swing.JLabel lb_contorno;
    private javax.swing.JLabel lb_criarconta;
    private javax.swing.JLabel lb_futuro;
    private javax.swing.JLabel lb_greenpeace;
    private javax.swing.JLabel lb_imgfloresta;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JPanel painel_mascara;
    private javax.swing.JSeparator sep_name;
    private javax.swing.JSeparator sep_senha;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
