/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;



/**
 *
 * @author TheLoli
 */
public class login extends javax.swing.JFrame {
    
  
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        sep_nome = new javax.swing.JSeparator();
        lb_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        sep_usuario = new javax.swing.JSeparator();
        lb_senha = new javax.swing.JLabel();
        txt_senha = new javax.swing.JPasswordField();
        sep_senha = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        sep_email = new javax.swing.JSeparator();
        br_criarconta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 32, 36));
        jPanel1.setForeground(new java.awt.Color(32, 32, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nome.setForeground(new java.awt.Color(115, 200, 44));
        lb_nome.setText("Nome");
        jPanel1.add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 10));

        txt_nome.setBackground(new java.awt.Color(51, 52, 54));
        txt_nome.setForeground(new java.awt.Color(255, 255, 255));
        txt_nome.setBorder(null);
        txt_nome.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 260, 30));
        jPanel1.add(sep_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 260, 10));

        lb_usuario.setForeground(new java.awt.Color(115, 200, 44));
        lb_usuario.setText("Usuário");
        jPanel1.add(lb_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 10));

        txt_usuario.setBackground(new java.awt.Color(51, 52, 54));
        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setBorder(null);
        txt_usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 260, 30));
        jPanel1.add(sep_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 260, 10));

        lb_senha.setForeground(new java.awt.Color(115, 200, 44));
        lb_senha.setText("Senha");
        jPanel1.add(lb_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 40, 10));

        txt_senha.setBackground(new java.awt.Color(51, 52, 54));
        txt_senha.setForeground(new java.awt.Color(255, 255, 255));
        txt_senha.setBorder(null);
        txt_senha.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 260, 30));
        jPanel1.add(sep_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 260, 10));

        jLabel3.setForeground(new java.awt.Color(115, 200, 44));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, 10));

        txt_email.setBackground(new java.awt.Color(51, 52, 54));
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(null);
        txt_email.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 260, 30));
        jPanel1.add(sep_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 260, 10));

        br_criarconta.setBackground(new java.awt.Color(115, 200, 44));
        br_criarconta.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        br_criarconta.setText("Criar conta");
        br_criarconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_criarcontaActionPerformed(evt);
            }
        });
        jPanel1.add(br_criarconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 260, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(380, 0, 450, 499);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/contornogreen.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 200, 44));
        jLabel2.setText("Greenpeace");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Harlow Solid Italic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Por um futuro menos poluído.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/floresta-amazonica-343759751.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void br_criarcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_criarcontaActionPerformed
            
    }//GEN-LAST:event_br_criarcontaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton br_criarconta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JSeparator sep_email;
    private javax.swing.JSeparator sep_nome;
    private javax.swing.JSeparator sep_senha;
    private javax.swing.JSeparator sep_usuario;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
